### PR TITLE
bb-org-overlays.bb: Added BB-UART4-RTSCTS-00A0.dts overlay

### PR DESCRIPTION
**Pull request by Sharvin26**
This overlay enables RTS/CTS flow control for UART4

Changelog-entry: bb-org-overlays.bb: Added BB-UART4-RTSCTS-00A0.dts overlay
Signed-off-by: Sharvin Shah sharvinshah51@gmail.com

### CODE REVIEW

**Comment by spanceac** [comment]
So `bb-org-overlays.bb: Added BB-UART4-RTSCTS-00A0.dts overlay` will be title and this will be commit text
```
This overlay enables RTS/CTS flow control for UART4

Changelog-entry: bb-org-overlays.bb: Added BB-UART4-RTSCTS-00A0.dts overlay
Signed-off-by: Sharvin Shah sharvinshah51@gmail.com
```

**Comment by Sharvin26** [comment]
I have updated the comment. Please verify the changes.

**Comment by spanceac** [comment]
hey @Sharvin26, what you did there doesn't reflect in the commit itself: https://github.com/balena-os/balena-beaglebone/pull/190/commits/1599886a04f198ffe00c4f9802bbd90e54e6204d

You should use `git commit --amend`, do the requested changes and then push again

**Comment by Sharvin26** [comment]
Okay I'll do that.

**Comment by Sharvin26** [comment]
I have made the changes and pushed the code. Please verify.

**Comment by spanceac** [comment]
hey @Sharvin26, now you have 3 commits instead of one.

Commit 0acd7a1bcf32711bb69b17b3a7762498e1c7ab92 is the good one.

Also, please forgive me for omitting but your e-mail address in `Signed-off-by` field should be in in angle brackets like this: `<sharvinshah51@gmail.com>`

Please add this modification and remove the 2 useless commits.

If it is too much trouble I will do a different PR containing your changes.

**Comment by spanceac** [comment]
If you do `git commit -s -m "your commit message"` the `Signed-off-by` field will be automatically added with your mail address

**Comment by Sharvin26** [comment]
Thanks for the help I have updated the PR.

**Comment by spanceac** [comment]
thanks @Sharvin26! It looks good now. When CI checks will pass, I will merge it

**Comment by spanceac** [comment]
@balena-ci retest this please

**Comment by Sharvin26** [comment]
Thanks for accepting the PR. Let me know once the PR with this version is available for download.

**Pull request merged**
