### PR TITLE
Update to kirkstone.

### PR DESCRIPTION
**Pull request by perezmeyer**
In order to make the beaglebone-ai64 to work it is first required to switch to meta-ti's kirkstone branch, so we need to update all the relevant layers.

We also need to manually remove kernel-related image/headers from MACHINE_ESSENTIAL_EXTRA_RDEPENDS.

On kirkstone meta-ti uses linux-bb.org, so we created a bbappend in order for it to inherit kernel-balena. This kernel might probably be used with the beaglebone AI64.

The kernel-modules-headers' bbappend is removed because the base recipe does not exists anymore on any layer.

Also remove beagleboard-xm.coffee, support was dropped by meta-ti on https://git.yoctoproject.org/meta-ti/commit/?id=209da2791f911235faaf4104ebf289b0e11d975b

Changelog-entry: Update layer to kirkstone

### CODE REVIEW

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Comment by perezmeyer** [comment]
@resin-jenkins retest this please

**Comment by perezmeyer** [comment]
@resin-jenkins test this please

**Comment by alexgg** [comment]
Leviathan failure:
```
jenkins-leviathan-v2-template-24569-client-1  | [2023-08-15T14:04:20.641Z][df30d27-os] StatusCodeError: 500 - "<!DOCTYPE html><html><head><meta charset=\"utf8\"><title>balena.io Device Public URLs</title><link rel=\"shortcut icon\" href=\"[https://balena.io/favicon.png\](https://balena.io/favicon.png/)"><link href=\"[https://maxcdn.bootstrapcdn.com/bootswatch/3.3.4/superhero/bootstrap.min.css\](https://maxcdn.bootstrapcdn.com/bootswatch/3.3.4/superhero/bootstrap.min.css/)" rel=\"stylesheet\"><style>body {\n\tbackground-color: #2d2d2c;\n}\nh1 {\n\tmargin: 1em 0;\n}\n.container {\n\tmax-width: 800px;\n}\n.btn {\n\tmax-width: 600px;\n\tmargin: auto;\n}\n.alert {\n\tfont-size: 130%;\n\tmargin: 2em 0;\n}\n.alert p {\n\tmargin-bottom: 1em;\n}\n.alert p:last-child {\n\tmargin-bottom: 0;\n}\n.logo {\n\tdisplay: inline-block;\n\theight: 1em;\n\tmargin-right: 0.4em;\n\tposition: relative;\n\ttop: -0.1em;\n}\n.footer {\n\tpadding: 0 15px;\n\tfont-size: 85%;\n\tfont-weight: normal;\n\tcolor: #565652;\n}\n.footer a {\n\tcolor: #565652;\n}</style></head><body><div class=\"container\"><h1><a href=\"[https://balena.io\](https://balena.io/)"><img class=\"logo\"
```

**Comment by alexgg** [comment]
@resin-jenkins retest this please

**Pull request merged**
