### PR TITLE
Do not merge: github workflow test

### PR DESCRIPTION
**Pull request by jadonk**
I don't want you to merge this, I just want to find out how to get this built. It seems the builds are going off to your Jenkins where I cannot see how to configure the build. I want to see if you are sharing access such that I can benefit from getting this built. Ideally, I can get a simple setup I can use to build either on Github or on Beagle's Gitlab instance.

### CODE REVIEW

**Comment by jadonk** [comment]
Is there any way to utilize the test build assets? Is there a way I can use CI to build it myself?

**Comment by jadonk** [comment]
yes, i need help doing that. i would prefer to do with CI rather than local.

**Comment by floion** [comment]
Hi @jadonk there are build instructions in the readme: https://github.com/balena-os/balena-beaglebone/blob/master/README.md#containerized-build

**Comment by alexgg** [comment]
hey @jadonk unfortunately until we transition the CI/CD out from Jenkins we don't have mechanisms to provide external access. However we would be keen on unblocking you - we could add you to our partners chat to give you direct access to developers if you think it would help.

**Comment by jadonk** [comment]
Please!

**Comment by alexgg** [comment]
hi @jadonk I have messaged to your user in forums.balena.io asking for an email address we can use to give you access to our external partners app. Would you please reply to that direct message, or let me know here if you haven't received it?
Thanks again.

**Pull request closed without merging**
