### PR TITLE
Beaglebone AI 64 support

### PR DESCRIPTION
**Pull request by perezmeyer**
Add support for the Beaglebone AI64 board. WIP.

### CODE REVIEW

**Comment by floion** [comment]
Hi, in addition to what I asked by e-mail, can you also check the u-boot conflict on this PR please?

**Comment by floion** [comment]
Hi @perezmeyer I think you can have this PR cleaned up so it can go through a final review.
Thanks!

**Comment by perezmeyer** [comment]
> Hi @perezmeyer I think you can have this PR cleaned up so it can go through a final review. Thanks!

I'm afraid this is not straightforward, at least yet. I tried building for the Beglebone Black with this changes and the kernel-modules-headers recipe fails to build because it fails to find the mpc.h header. But both libmpc and libmpc-native are there... so at this point this PR is not fit for the BBB.

**Comment by jontrulson** [comment]
Not to mention we still have not been able to complete a build for the BB-AI64:)

**Comment by floion** [comment]
@jontrulson what are the outstanding issues? I somehow was under the impression the build went through fine

**Comment by jontrulson** [comment]
Oh - no, we haven't had it building successfully yet - I was wondering why you wanted us to submit this PR in it's current state :)

The upgrade to kirkstone broke the other boards (mpc.h failure). I think Lisandro is looking at that.

But for the AI64, with the two patches I have in the PR, I last left it with a failure in do_rootfs:

```
ERROR: balena-image-1.0-r0 do_rootfs: Unable to install packages. Command '/data/yoctos/balena-docker/tmp/work/beaglebone_ai64-poky-linux/balena-image/1.0-r0/recipe-sysroot-native/usr/bin/opkg --volatile-cache -f /data/yoctos/balena-docker/tmp/work/beaglebone_ai64-poky-linux/balena-image/1.0-r0/opkg.conf -t /data/yoctos/balena-docker/tmp/work/beaglebone_ai64-poky-linux/balena-image/1.0-r0/temp/ipktemp/ -o /data/yoctos/balena-docker/tmp/work/beaglebone_ai64-poky-linux/balena-image/1.0-r0/rootfs  --force_postinstall --prefer-arch-to-version  --add-exclude kernel-image-image-* --add-exclude kernel-image-image-* --add-ignore-recommends shared-mime-info install bb-wl18xx-btwl beagle-serial kernel-devicetree kernel-image-initramfs libnss-ato packagegroup-balena-connectivity packagegroup-core-boot packagegroup-core-ssh-openssh packagegroup-resin packagegroup-resin-debugtools plymouth plymouth-balena-theme run-postinsts wlconf' returned 1:
 * Solver encountered 1 problem(s):
 * Problem 1/1:
 *   - package packagegroup-core-boot-1.0-r17.beaglebone_ai64 requires kernel-image-image, but none of the providers can be installed
 *   - package kernel-image-image-5.10.162-5.10.162+git0+a2f5d5746b-r0.beaglebone_ai64 can only be installed by a direct request
 *   - conflicting requests
 * 
 * Solution 1:
 *   - install kernel-image-image-5.10.162-5.10.162+git0+a2f5d5746b-r0.beaglebone_ai64

 * Solution 2:
 *   - do not ask to install a package providing packagegroup-core-boot
 * ...
```

This seems to be a result of:

_./layers/meta-balena/meta-balena-kirkstone/classes/kernel-balena-noimage.bbclass_

Which I'm not sure how to resolve.

I hope to have some time to revisit  this later this week or early next week.  Suggestions welcome.

**Comment by floion** [comment]
Looking at the reported package name, `kernel-image-image`, it looks to me that the name is parsed kinda funny. So it seems like a variable expansion is not done properly. And I remember seeing something similar recently in another board. @acostach do you remember something like this?

**Comment by acostach** [comment]
Hi @jontrulson,  looks like the yocto machine.conf for the beaglebone-ai adds: 

```
MACHINE_ESSENTIAL_EXTRA_RDEPENDS += "kernel-devicetree kernel-image-image"
```

in https://git.yoctoproject.org/meta-ti/commit/?h=kirkstone&id=38941472e1e30c57f89115a28ea751f5ae535bb2

but the kernel-image-initramfs used by BalenaOS is already included by the corresponding OS [packagegroup](https://github.com/balena-os/meta-balena/blob/master/meta-balena-common/recipes-core/packagegroups/packagegroup-resin.inc#L18) so there's no reason to install the 'kernel-image-image' package. Therefore, to get rid of this error, you can add the following line to meta-balena-beaglebone/conf/layer.conf:

```
MACHINE_ESSENTIAL_EXTRA_RDEPENDS:remove = "kernel-image-image"
```

cc @perezmeyer

**Comment by perezmeyer** [comment]
> but the kernel-image-initramfs used by BalenaOS is already included by the corresponding OS [packagegroup](https://github.com/balena-os/meta-balena/blob/master/meta-balena-common/recipes-core/packagegroups/packagegroup-resin.inc#L18) so there's no reason to install the 'kernel-image-image' package.

Thanks, that is definitely a piece of information we where missing.

**Comment by jontrulson** [comment]
@acostach Thanks for the tip!  That did allow me to get past do_rootfs(), but failed with:

```
ERROR: balena-image-1.0-r0 do_resin_boot_dirgen_and_deploy: /data/yoctos/balena-docker/deploy/images/beaglebone-ai64/extra_uEnv.txt is an invalid path referenced in BALENA_BOOT_PARTITION_FILES.
ERROR: balena-image-1.0-r0 do_resin_boot_dirgen_and_deploy: ExecutionError('/data/yoctos/balena-docker/tmp/work/beaglebone_ai64-poky-linux/balena-image/1.0-r0/temp/run.do_resin_boot_dirgen_and_deploy.20475', 1, None, None)
ERROR: Logfile of failure stored in: /data/yoctos/balena-docker/tmp/work/beaglebone_ai64-poky-linux/balena-image/1.0-r0/temp/log.do_resin_boot_dirgen_and_deploy.20475
ERROR: Task (/home/jon/m5-ics/balena/src/balena-beaglebone/build/../layers/meta-balena/meta-balena-common/recipes-core/images/balena-image.bb:do_resin_boot_dirgen_and_deploy) failed with exit code '1'
```

Indeed, that file does not exist in the deploy dir.  I didn't have much time tonight to investigate further, but that did get me farther.  Thanks!

**Comment by perezmeyer** [comment]
@jontrulson that is actually the same error I get if I remove kernel-image-zimage tand kernel-modules-headers from the BBB's build, so whatever we are dealing with here seems to have a common root.

**Comment by jontrulson** [comment]
Yes, u-boot was already build for me too, and rebuilding virtual/bootloader changed nothing.

**Comment by perezmeyer** [comment]
Closing this one as comes from external repo, switching to one coming as a branch of this repo.

**Pull request closed without merging**
