### PR TITLE
README.md update to match the directory names

### PR DESCRIPTION
**Pull request by Rafq77**
Change-type: hotfix 

Changelog-entry: Update directory names in README.md
Signed-off-by: Rafal Sokolowski <sokol-77@wp.pl>

### CODE REVIEW

**Comment by floion** [comment]
Hi and thanks for the pull request. I need to point out that we use strict commit guidelines for our repositories. The is info in the README section https://github.com/balena-os/balena-beaglebone#contributing but this needs a small update. So you can use this one which is up to date: https://github.com/balena-os/balena-intel#contributing
As an example, see https://github.com/balena-os/balena-intel/pull/240/commits/ad19d70d96c32bbd87bda2b2b377657c4d2f5511 but note that in addition you would also need to add a `Changelog-entry` field as each pull request needs at least 1 such entry in it.

**Comment by Rafq77** [comment]
Hi @floion, thank you for your check. I might as well copy/merge(?) the contribution part of [README.md from balena-intel](https://github.com/balena-os/balena-intel/blob/master/README.md), because I tried to write comment based of the [README from balena-beaglebone](https://github.com/balena-os/balena-beaglebone#contributing). 

I added `Changelog-entry` as requested.

**Comment by floion** [comment]
Yes you can copy from there. However, this pull request still needs rework. Read carefully the instructions. For example, it says there the git log commit must be in the form "component: Short description" (https://github.com/balena-os/balena-intel#pull-requests).
And since you need to rework, you can do this in just 1 commit, instead of 2.

**Comment by Rafq77** [comment]
Sorry, I'm pretty new to this. Should I then amend the existing 2 commits and force push on the branch? Will this be reflected in this pull request accordingly?

**Comment by Rafq77** [comment]
@floion ;)

**Comment by floion** [comment]
Can you to both changes in the same commit? You need to rebase with current master anyway: `git checkout master && git pull && git checkout readme-update && git rebase master`
And then you can squash the 2 commits into just 1. And also, don't forget, no more than 72 chars per line.

**Comment by Rafq77** [comment]
Merged into 1, and checked the chars limit.

**Comment by floion** [comment]
@resin-jenkins ok to test

**Comment by floion** [comment]
Was still missing the rebase onto current master but I updated it through github. It will show an ugly merge commit but we can live with it. Thanks for the contribution.

**Comment by Rafq77** [comment]
Thank you for your patience and support during this PR.

**Comment by floion** [comment]
@balena-ci retest

**Comment by floion** [comment]
One more thing, sorry about that. The `Changelog-entry` can be longer than 72 chars. And having a new line there actually makes out checker throw an error. Can you change that please?

**Comment by Rafq77** [comment]
Forced, w-out rebase. Is that better?

**Comment by floion** [comment]
@balena-ci retest

**Pull request merged**
