### PR TITLE
Update bb kernel to 5.10.162 ti r59

### PR DESCRIPTION
**Pull request by floion**

### CODE REVIEW

**Comment by floion** [comment]
Depends on https://github.com/balena-os/balena-beaglebone/pull/538

**Comment by svwspencer** [comment]
I checked out this merge request and merged it with https://github.com/balena-os/balena-beaglebone/pull/538 . I'm noticing a couple issues. I was able to load in the PRU device tree overlay and start a PRU image. However when I try to use read/write to the remote procedure device (/dev/rpmsg_pru30) , it does not work . I get this kernel crash in dmesg. The pru image works fine on debian reference image from TI as well as the current build from dev.

`[  325.446629] 8<--- cut here ---
[  325.452623] Unable to handle kernel NULL pointer dereference at virtual address 00000000
[  325.465938] pgd = a72209ce
[  325.469324] [00000000] *pgd=00000000
[  325.473501] Internal error: Oops: 5 [#3] PREEMPT SMP ARM
[  325.479065] Modules linked in: rpmsg_pru virtio_rpmsg_bus(+) rpmsg_core ip6t_REJECT nf_reject_ipv6 ipt_REJECT nf_reject_ipv4 ip6table_filter ip6_tables xt_MASQUERADE nf_conntrack_netlink nfnetlink xfrm_user xfrm_algo br_netfilter xt_owner wl18xx wlcore mac80211 cfg80211 libarc4 hci_uart btqca btrtl btbcm btintel rfcomm bluetooth pru_rproc irq_pruss_intc pm33xx pruss ti_eqep counter c_can_platform c_can can_dev spidev evdev wkup_m3_ipc uio_pdrv_genirq uio cpufreq_dt sch_fq_codel
[  325.523384] CPU: 0 PID: 1487 Comm: sh Tainted: G      D           5.10.162+ #1
[  325.530910] Hardware name: Generic AM33XX (Flattened Device Tree)
[  325.537275] PC is at pru_rproc_kick+0x5c/0x104 [pru_rproc]
[  325.542993] LR is at 0xc5533248
[  325.546264] pc : [<bf0695e8>]    lr : [<c5533248>]    psr: 80000013
[  325.552791] sp : c473de20  ip : c473de28  fp : 00000000
[  325.558233] r10: 00000004  r9 : 00000015  r8 : c4577ca4
[  325.563674] r7 : bf321308  r6 : c1bdb5f4  r5 : c55332f0  r4 : c5533020
[  325.570474] r3 : 00000000  r2 : 00000001  r1 : 00000000  r0 : bf06b084
[  325.577275] Flags: Nzcv  IRQs on  FIQs on  Mode SVC_32  ISA ARM  Segment none
[  325.584706] Control: 10c5387d  Table: 82eb0019  DAC: 00000051
[  325.590693] Process sh (pid: 1487, stack limit = 0x14f0f4c9)
[  325.596590] Stack: (0xc473de20 to 0xc473e000)
[  325.601131] de20: dc906000 00000000 bf06b084 bf06b088 bf06b08c c250c848 c5533000 00000001
[  325.609656] de40: dc906000 c0c0ce48 c4577b80 00000000 dc906000 c086fdb8 c4577c80 bf324ab8
[  325.618178] de60: 00000cc0 00000000 00000000 00000000 00000400 0000001e bf321308 c1bda000
[  325.626701] de80: dfd654da 00000000 00000015 00000000 00000002 c250c848 c1186cc4 00000005
[  325.635226] dea0: 025303d0 c1b9e240 bf321308 00000051 bf31f4e8 00000004 00000000 bf324d8c
[  325.643747] dec0: 00000005 00000001 00000005 bf31f598 6453e0c4 c4f3b000 c4f3b000 00000000
[  325.652266] dee0: 00000005 025303d0 c473df78 c034b8d8 c4f3b000 c4f3b000 00000001 00000036
[  325.660786] df00: 00000000 c06a2db0 00005401 b6fe43a0 c4f3b000 be8d839c c4f3b000 c0361dc4
[  325.669308] df20: 00201000 00000000 00000176 00000000 00000005 0ec00000 00000000 00000000
[  325.677830] df40: 00000000 00000000 6453e0c4 c250c848 00000005 c4f3b000 c4f3b000 00000000
[  325.686351] df60: 00000000 025303d0 00000005 00000004 00000000 c034d374 00000000 00000000
[  325.694871] df80: 00000000 c250c848 b6fe43a0 00000005 025303d0 b6fe43a0 00000004 c01002c4
[  325.703393] dfa0: c473c000 c0100060 00000005 025303d0 00000001 025303d0 00000005 00000000
[  325.711917] dfc0: 00000005 025303d0 b6fe43a0 00000004 b6f7a594 b6f7a0fc 00000000 00000000
[  325.720439] dfe0: 00000004 be8d8970 b6f1847f b6ea4066 40000030 00000001 00000000 00000000
[  325.728988] [<bf0695e8>] (pru_rproc_kick [pru_rproc]) from [<c0c0ce48>] (rproc_virtio_notify+0x2c/0x54)
[  325.738786] [<c0c0ce48>] (rproc_virtio_notify) from [<c086fdb8>] (virtqueue_kick+0x34/0x50)
[  325.747519] [<c086fdb8>] (virtqueue_kick) from [<bf324ab8>] (rpmsg_send_offchannel_raw+0x1c0/0x37c [virtio_rpmsg_bus])
[  325.758683] [<bf324ab8>] (rpmsg_send_offchannel_raw [virtio_rpmsg_bus]) from [<bf324d8c>] (virtio_rpmsg_send+0x30/0x38 [virtio_rpmsg_bus])
[  325.771649] [<bf324d8c>] (virtio_rpmsg_send [virtio_rpmsg_bus]) from [<bf31f598>] (rpmsg_pru_write+0xb0/0x15c [rpmsg_pru])
[  325.783188] [<bf31f598>] (rpmsg_pru_write [rpmsg_pru]) from [<c034b8d8>] (vfs_write+0xc8/0x488)
[  325.792257] [<c034b8d8>] (vfs_write) from [<c034d374>] (ksys_write+0x64/0xec)
[  325.799696] [<c034d374>] (ksys_write) from [<c0100060>] (ret_fast_syscall+0x0/0x54)
[  325.807669] Exception stack(0xc473dfa8 to 0xc473dff0)
[  325.812932] dfa0:                   00000005 025303d0 00000001 025303d0 00000005 00000000
[  325.821455] dfc0: 00000005 025303d0 b6fe43a0 00000004 b6f7a594 b6f7a0fc 00000000 00000000
[  325.829973] dfe0: 00000004 be8d8970 b6f1847f b6ea4066
[  325.835240] Code: e320f000 e5953054 e3a02001 e3a01000 (e5930000) 
[  325.847623] ---[ end trace 7779fb9fc19f576c ]---
`

**Comment by svwspencer** [comment]
I'm also having trouble getting the eqep driver to work right. I see the devices in the file system and I can enable the eqep device. But I'm not actually getting the counts. I made sure to properly set the pin muxing as well.

**Comment by floion** [comment]
About the kernel crash when using the PRU image. Can you share the steps to reproduce?

**Comment by svwspencer** [comment]
> About the kernel crash when using the PRU image. Can you share the steps to reproduce?

I used the following uEnv.txt

```
enable_uboot_overlays=1
disable_uboot_overlay_video=1
disable_uboot_overlay_audio=1
disable_uboot_overlay_wireless=1
disable_uboot_overlay_adc=1
uboot_overlay_pru=/boot/overlays/AM335X-PRU-RPROC-4-19-TI-00A0.dtbo
cmdline=coherent_pool=1M net.ifnames=0 lpj=1990656 rng_core.default_quality=100 quiet
```

I created a container with the following Dockerfile to create a container that has much of the same as the following to get similar SDK software as what's available on the reference debian image

```
FROM balenalib/beaglebone-black-debian:buster as base
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y build-essential ca-certificates ti-pru-cgt-installer bb-customizations bb-cape-overlays pru-software-support-package bone101 xxd
```

Inside the containers I built this project (https://github.com/RoSchmi/Beaglebone-PRU-RPMsg-HelloWorld) to test the rpmsg between the host os and pru units. The pru code that's loaded to both pru units simply echo strings received by them. When writing a small string to /dev/rpmsg_pru30 my ssh sessions is killed and I get that kind of kernel error message in dmesg.

**Comment by floion** [comment]
@svwspencer could you provide the complete Dockerfile you used? Need to have your exact steps to reproduce the issue

**Comment by svwspencer** [comment]
Regarding the eqep driver, that does work once I found the proper incantation to get it to work. Aside from loading in the proper device tree overlay, it also needs to have it's maximum value set so it can not be 0.

The rpmsg driver still seems to be an issue. I'll leave it to you to decide if it should hold up upgrading the kernel or if it should become it's own known issue.

**Comment by svwspencer** [comment]
@floion  I looked into this again and got a little advice from Robert Nelson about using rpmsg here (https://github.com/RobertCNelson/ti-linux-kernel-dev/issues/54 ) with the 5.10 kernel .  I merged this branch with master on my own and was able to get the rpmsg feature to work just fine following his guidance. I now have no qualms about this merge request.

**Comment by floion** [comment]
@balena-ci I self-certify!

**Comment by floion** [comment]
@svwspencer thanks for the follow-up. Had not got on my part to do actual investigation on the rpmsg feature so much appreciated you chased it and figured it out.

**Comment by floion** [comment]
@resin-jenkins add to whitelist

**Pull request merged**
